name: CI
on: push

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Noe.js 18.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Noe.js 18.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
